project:
  type: website

website:
  title: "Shun's Personal Hub"

  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Links"
        href: links.qmd
      - text: "Contact"
        href: contact.qmd

  page-footer:
    left:
      - text: "© 2026 Shun Yamaguchi"
    right:
      - text: "☕️ Buy me a coffee"
        href: https://ko-fi.com/shuny

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false