project:
  type: website

website:
  title: "Shun's Personal Hub"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: links.qmd
        text: Links
      - href: contacts.qmd
        text: Contact
    
  page-footer:
    left:
      - text: © 2026 Shun Yamaguchi
    right:
      - text: Buy me a coffee
        href: https://ko-fi.com/shuny/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



